kind: Pod
apiVersion: v1
metadata:
  name: pod-secrets
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: expense-secrets