kind: Pod
apiVersion: v1
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    envfrom:
    - configMapRef:
        name: expense-config